# week08/.github/workflows/frontend-cd.yml

name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: External IP of Product Service (e.g., http://x.x.x.x:8000)
        required: true
        default: 'http://<ip_address>:8000'
      order_api_ip:
        description: External IP of Order Service (e.g., http://x.x.x.x:8001)
        required: true
        default: 'http://<ip_address>:8001'
      aks_cluster_name:
        description: Name of the AKS Cluster
        required: true
        default: '<aks_name>'
      aks_resource_group:
        description: Resource Group of the AKS Cluster
        required: true
        default: '<resource_group_name>'

  workflow_call:
    inputs:
      product_api_ip:
        required: true
        type: string
      order_api_ip:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      aks_resource_group:
        required: true
        type: string

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Inject Backend IPs into frontend/main.js
        run: |
          echo "Injecting API URLs"
          sed -i "s|_PRODUCT_API_URL_|${{ inputs.product_api_ip }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|${{ inputs.order_api_ip }}|g" frontend/main.js
          echo "----- main.js -----"
          tail -n +1 frontend/main.js
          echo "-------------------"

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest ./frontend
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest

  deploy_frontend:
    needs: build_and_push_frontend
    uses: ./.github/workflows/_deploy-aks.yml
    with:
      aks_cluster_name:   ${{ inputs.aks_cluster_name }}
      aks_resource_group: ${{ inputs.aks_resource_group }}
      manifests_path:     k8s/
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
